### ISSUE TITLE
Fluentd agent log paths are hard coded

### ISSUE THREAD

**Issue by bhourigan** [Nubisproject/nubis-base#92]
I think the paths are Ubuntu specific:

```
$ grep /var/log fluentd.pp
    'path'     => '/var/log/syslog',
    'path'     => '/var/log/kern.log',
    'path'     => '/var/log/mail.log',
    'path'     => '/var/log/mail.err',
```

There are many other log files which exist on Amazon Linux and we are not forwarding them.

**Comment by bhourigan** [comment]
Looking at the fluentd input documentation I think the pos_file parameter needs to be unique for each log source. It is currently shared between all sources.

Rather than the tail input module, it might be better to use the in_syslog module:

http://docs.fluentd.org/articles/in_syslog

**Comment by gozer** [comment]
pos_file most definitely needs to be different, that's a bug, and I'll fix it.

As for the tail stuff, I agree it is hard-coded, and should be fixed.

As for using in_syslog, that's probably a good idea to include it, but it isn't a solution for all, since it just exposes a syslog server endpoint. Apache logs, for example, will still need to be comsumed by tailing them.

**Comment by bhourigan** [comment]
Yeah it is not a solution for everything, but it would eliminate the need for OS specific logic to include system logs. It was just a suggestion.

**Comment by gozer** [comment]
Just realized we could just remove/disable syslog on our images completely! And replace with in_syslog...

**Comment by gozer** [comment]
For Amazon Linux, this needs to be : 
 - /var/log/messages
 - /var/log/secure
 - /var/log/maillog
 - /var/log/cron
 - /var/log/spooler
 - /var/log/boot.log
